using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace WebUntisAPI.Client.Models;

/// <summary>
/// Represents credentials that can be used to sign in a user
/// </summary>
public class AppCredentials
#if NET7_0_OR_GREATER
    : IParsable<AppCredentials>
#endif
{
    /// <summary>
    /// The host name of the server
    /// </summary>
    [JsonProperty("url")]
    public string ServerName { get; set; } = string.Empty;

    /// <summary>
    /// The name of the school to sign in
    /// </summary>
    [JsonProperty("school")]
    public string School { get; set; } = string.Empty;

    /// <summary>
    /// The id of the school to sign in
    /// </summary>
    [JsonProperty("schoolNumber")]
    public int SchoolId { get; set; }

    /// <summary>
    /// The username of the user to sign in
    /// </summary>
    [JsonProperty("user")]
    public string Username { get; set; } = string.Empty;

    /// <summary>
    /// The secret key that is used to sign in
    /// </summary>
    [JsonProperty("key")]
    public string Key { get; set; } = string.Empty;

    private const string _parseRegEx = @"^untis:\/\/setschool\?(?:(\w+?=[\w\d\s-\.]+)&?){5,}$";

    /// <summary>
    /// Parses an uri contained in a qr code generated by untis
    /// </summary>
    /// <param name="s">The uri of the qr code</param>
    /// <param name="provider">A format provider but here is it never used</param>
    /// <returns>The parsed Credentials</returns>
    /// <exception cref="FormatException"></exception>
    /// <exception cref="ArgumentException"></exception>
    [SuppressMessage("Style", "IDE0060", Justification = "Parameter required for IParsable<AppCredentials> from .NET 7.")]
    public static AppCredentials Parse(string s, IFormatProvider? provider)
    {
        Match match = Regex.Match(s, _parseRegEx);
        if (!match.Success)
            throw new FormatException($"The specified parameter {nameof(s)} have to match this RegEx {_parseRegEx}");

        ImmutableDictionary<string, string> queryParams = match.Groups[1].Captures
            .Select(capture => capture.Value.Split('=', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries))
            .ToImmutableDictionary(source => source[0], source => source[1]);

        if (!(queryParams.ContainsKey("url") && queryParams.ContainsKey("school") && queryParams.ContainsKey("user") && queryParams.ContainsKey("key") && queryParams.ContainsKey("schoolNumber")))
            throw new ArgumentException("The does not contains the required query params 'url', 'school', 'user', 'key' and 'schoolNumber'.");

        if (!int.TryParse(queryParams["schoolNumber"], out int schoolId))
            throw new ArgumentException("The query param 'schoolNumber' have to be an integer.");

        return new()
        {
            ServerName = queryParams["url"],
            School = queryParams["school"],
            SchoolId = schoolId,
            Username = queryParams["user"],
            Key = queryParams["key"]
        };
    }

    /// <summary>
    /// Tries to parse an uri contained in a qr code generated by untis
    /// </summary>
    /// <param name="s">The uri of the qr code</param>
    /// <param name="provider">A format provider but here is it never used</param>
    /// <param name="result">The result of the parse. When <c>null</c> is returned then this will be <c>null</c></param>
    /// <returns>Indicates whether the parse were successful</returns>
    /// <exception cref="FormatException"></exception>
    /// <exception cref="ArgumentException"></exception>
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out AppCredentials result)
    {
        if (string.IsNullOrEmpty(s))
        {
            result = null;
            return false;
        }

        try
        {
            result = Parse(s, provider);
            return true;
        }
        catch
        {
            result = null;
            return false;
        }
    }

    /// <summary>
    /// Creates an uri that contains the credentials of this instance. A qr code that contains this uri can used to sign in into untis
    /// </summary>
    /// <returns>The uri</returns>
    /// <exception cref="ArgumentException"></exception>
    public Uri CreateQrCodeUri()
    {
        if (Uri.CheckHostName(ServerName) is UriHostNameType.Unknown or UriHostNameType.Basic)
            throw new ArgumentException("The server name have to be a valid host name.", nameof(ServerName));

        string uriString = $"untis://setschool?url={ServerName}&school={School}&user={Username}&key={Key}&schoolNumber={SchoolId}";
        return new Uri(uriString, UriKind.Absolute);
    }
}
