using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WebUntisAPI.Client.Models;

/// <summary>
/// Provides the result of a sign in attempt
/// </summary>
public class SignInResult
{
    /// <summary>
    /// Indicates whether the sign in were successfully
    /// </summary>
    public bool Successful { get; init; }

    /// <summary>
    /// Indicates whether the provided credentials were wrong
    /// </summary>
    public bool BadCredentials { get; init; }

    /// <summary>
    /// Indicates whether the provided school name were not found
    /// </summary>
    public bool SchoolNotFound { get; init; }

    /// <summary>
    /// Indicates whether the sign in requires the mfa token generated by the users mfa application
    /// </summary>
    public bool RequireMfa { get; init; }

    /// <summary>
    /// Indicates whether the provided mfa token were invalid
    /// </summary>
    public bool InvalidMfaToken { get; init; }
}