using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OtpNet;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using System.Reflection;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using WebUntisAPI.Client.Exceptions;
using WebUntisAPI.Client.Models;
using WebUntisAPI.Client.Models.Elements;
using WebUntisAPI.Client.Models.Interfaces;

namespace WebUntisAPI.Client;

/// <summary>
/// A client that connect to a WebUntis server to load data
/// </summary>
public partial class WebUntisClient : IDisposable
{
    /// <summary>
    /// Indicates whether the client is currently logged in
    /// </summary>
    [MemberNotNullWhen(true, nameof(Session))]
    public bool IsLoggedIn => _session is not null;

    /// <summary>
    /// The current active session.
    /// </summary>
    public WebUntisSession? Session => _session;
    private WebUntisSession? _session;

    private readonly HttpClient _client;
    private readonly bool _disposeClient;

    /// <summary>
    /// Creates a new instance that creates its own <see cref="HttpClient"/> that uses a timeout of 5s and a user agent in the format of WebUntisAPI.Client/{version}
    /// </summary>
    public WebUntisClient() : this(TimeSpan.FromSeconds(5))
    {
    }

    /// <summary>
    /// Creates a new instance that creates its own <see cref="HttpClient"/> that uses the specified timeout and a user agent in the format of WebUntisAPI.Client/{version}
    /// </summary>
    /// <param name="timeout">The timeout for every request</param>
    /// <exception cref="ArgumentNullException"></exception>
    /// <exception cref="ArgumentOutOfRangeException"></exception>
    public WebUntisClient(TimeSpan timeout)
    {
        ArgumentNullException.ThrowIfNull(timeout, nameof(timeout));
        if (timeout <= TimeSpan.Zero)
            throw new ArgumentOutOfRangeException(nameof(timeout), "The timeout have to be larger than 0.");

        _client = new()
        {
            Timeout = timeout
        };

        AssemblyName assemblyName = typeof(WebUntisClient).Assembly.GetName();
        _client.DefaultRequestHeaders.UserAgent.Add(new(assemblyName.Name!, assemblyName.Version?.ToString()));
    }

    /// <summary>
    /// Creates a new instance that uses a provided <see cref="HttpClient"/> instance
    /// </summary>
    /// <param name="client">A client instance to use</param>
    /// <param name="disposeClient">Indicates whether the client should disposed when this instance will be disposed</param>
    /// <exception cref="ArgumentNullException"></exception>
    public WebUntisClient(HttpClient client, bool disposeClient)
    {
        ArgumentNullException.ThrowIfNull(_client, nameof(_client));

        _client = client;
        _disposeClient = disposeClient;
    }

    /// <summary>
    /// Signs in a user
    /// </summary>
    /// <remarks>
    /// A thrown <see cref="WebUntisException"/> that contains an error with the <see cref="WebUntisError.Code"/> <c>SCHOOL_NOT_FOUND</c> means that <paramref name="school"/> is invalid
    /// </remarks>
    /// <param name="school">The school to login</param>
    /// <param name="username">Name of the user to login</param>
    /// <param name="password">Password of the user to login</param>
    /// <param name="mfaToken">An Totp token generated by the users mfa application. When the account to sign in doesn't have Totp mfa enabled set this <c>null</c></param>
    /// <param name="ct">Cancelation Token</param>
    /// <returns><see langword="true"/> when the login was successful. <see langword="false"/> when the <paramref name="username"/> or <paramref name="password"/> was invalid</returns>
    /// <exception cref="ArgumentNullException"></exception>
    /// <exception cref="HttpRequestException"></exception>
    /// <exception cref="WebUntisException"></exception>
    /// <exception cref="ObjectDisposedException"></exception>
    public async Task<SignInResult> SignInAsync(School school, string username, string password, string? mfaToken, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(school, nameof(school));

        return await SignInAsync(school.Server, school.LoginName, username, password, mfaToken, ct);
    }

    /// <summary>
    /// Signs in a user
    /// </summary>
    /// <remarks>
    /// A thrown <see cref="WebUntisException"/> that contains an error with the <see cref="WebUntisError.Code"/> <c>-8500</c> means that <paramref name="loginName"/> is invalid
    /// </remarks>
    /// <param name="server">server name to login (example: <c>herakles.webuntis.com</c>)</param>
    /// <param name="loginName">School to login (<see cref="School.LoginName"/>)</param>
    /// <param name="username">Name of the user to login</param>
    /// <param name="password">Password of the user to login</param>
    /// <param name="mfaToken">An Totp token generated by the users mfa application. When the account to sign in doesn't have Totp mfa enabled set this <c>null</c></param>
    /// <param name="ct">Cancelation Token</param>
    /// <returns><c>true</c> when the login was successful. <c>false</c> when the <paramref name="username"/> or <paramref name="password"/> was invalid or the client were already logged in</returns>
    /// <exception cref="ArgumentNullException"></exception>
    /// <exception cref="HttpRequestException"></exception>
    /// <exception cref="WebUntisException"></exception>
    /// <exception cref="ObjectDisposedException"></exception>
    public async Task<SignInResult> SignInAsync(string server, string loginName, string username, string password, string? mfaToken, CancellationToken ct = default)
    {
        // Check for disposing
#if NET8_0_OR_GREATER
            ObjectDisposedException.ThrowIf(_disposedValue, this);
#else
        if (_disposedValue)
            throw new ObjectDisposedException(GetType().FullName);
#endif
        ArgumentNullException.ThrowIfNull(server, nameof(server));
        if (Uri.CheckHostName(server) is UriHostNameType.Unknown or UriHostNameType.Basic)
            throw new ArgumentException("The parameter have to be a valid hostname.", nameof(server));

        ArgumentNullException.ThrowIfNull(loginName, nameof(loginName));
        ArgumentNullException.ThrowIfNull(username, nameof(username));
        ArgumentNullException.ThrowIfNull(password, nameof(password));

        if (!string.IsNullOrEmpty(mfaToken))
        {
            if (mfaToken.Length != 6)
                throw new ArgumentException("The provided mfa token have to be a length of 6 chars.");
        }

        if (IsLoggedIn)
            throw new InvalidOperationException($"The client is already signed in. Use {nameof(SignOutAsync)} to sign out.");

        using HttpRequestMessage request = new(HttpMethod.Post, new UriBuilder
        {
            Scheme = Uri.UriSchemeHttps,
            Host = server,
            Path = "/WebUntis/j_spring_security_check"
        }.Uri)
        {
            Content = new FormUrlEncodedContent(new KeyValuePair<string, string>[]
            {
                new("school", loginName),
                new("j_username", username),
                new("j_password", password),
                new("token", mfaToken ?? string.Empty)
            })
        };

        using HttpResponseMessage response = await _client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, ct);
        response.EnsureSuccessStatusCode();

        // determine the sign in result by the uri of the redirects
        SignInResult result = response.RequestMessage?.RequestUri?.PathAndQuery switch
        {
            "/" => new() { SchoolNotFound = true },
            "/WebUntis/" => new() { BadCredentials = true },
            "/WebUntis/index.do" => new() { Successful = true },
            "/WebUntis/j_spring_security_check" => await CreateMfaResultAsync(),     // the original request uri means that there were no redirect and there is a problem with the mfa authentication
            _ => throw new Exception("Unable to determine the result of the sign in attempt.")
        };

        // Creates session from response if successful
        if (result.Successful)
        {
            WebUntisSession session = await CreateSessionInternalAsync(server, ct);
            _session = session;

            string appDataResponse = await InternalApiRequestAsync("/WebUntis/api/rest/view/v1/app/data", ct);
            JObject userData = (JObject)JObject.Parse(appDataResponse)["user"]!;
            if (userData["roles"]!.ToObject<string[]>()!.Contains("STUDENT"))
            {
                session._user = new Student
                {
                    Id = userData["person"]!["id"]!.Value<int>(),
                    Name = userData["name"]!.Value<string>()!,
                    Displayname = userData["person"]!["displayName"]!.Value<string>()!
                };
            }
            else
            {
                session._user = new Teacher
                {
                    Id = userData["person"]!["id"]!.Value<int>(),
                    Name = userData["name"]!.Value<string>()!,
                    Displayname = userData["person"]!["displayName"]!.Value<string>()!
                };
            }
            _session = session;
        }

        return result;

        // used to parse the mfa problem inside the switch expression
        async Task<SignInResult> CreateMfaResultAsync()     
        {
            string responseString = await response.Content.ReadAsStringAsync(ct);
            JObject responseJson = JObject.Parse(responseString);

            return new()
            {
                RequireMfa = responseJson["state"]!.Value<string>()!.Equals("TOKEN_REQUIRED"),
                InvalidMfaToken = responseJson["invalidToken"]!.Value<bool>()!
            };
        }
    }

    /// <summary>
    /// Signs in a user
    /// </summary>
    /// <param name="credentials">App credentials that were requested in recent session or were read from a qr code.</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A lot of general data that were send by the server. Is <c>null</c> when the login attempt failed.</returns>
    /// <exception cref="ArgumentNullException"></exception>
    /// <exception cref="HttpRequestException"></exception>
    /// <exception cref="WebUntisException"></exception>
    /// <exception cref="ObjectDisposedException"></exception>
    public async Task<MasterData?> SignInAsync(AppCredentials credentials, CancellationToken ct = default)
    {
        // Check for disposing
#if NET8_0_OR_GREATER
            ObjectDisposedException.ThrowIf(_disposedValue, this);
#else
        if (_disposedValue)
            throw new ObjectDisposedException(GetType().FullName);
#endif
        ArgumentNullException.ThrowIfNull(credentials.ServerName, nameof(credentials));
        if (Uri.CheckHostName(credentials.ServerName) is UriHostNameType.Unknown or UriHostNameType.Basic)
            throw new ArgumentException("The ServerName have to be a valid hostname.", nameof(credentials));

        if (IsLoggedIn)
            throw new InvalidOperationException($"The client is already signed in. Use {nameof(SignInAsync)} to sign out.");

        byte[] secretBytes = Base32Encoding.ToBytes(credentials.Key);
        Totp totpGenerator = new(secretBytes, 30, totpSize: 6);

        JArray requestParams = new()
        {
            new JObject
            {
                new JProperty("auth", new JObject
                {
                    new JProperty("clientTime", DateTimeOffset.Now.ToUnixTimeMilliseconds()),
                    new JProperty("user", credentials.Username),
                    new JProperty("otp", totpGenerator.ComputeTotp())
                })
            }
        };
        Uri requestUri = new UriBuilder
        {
            Scheme = Uri.UriSchemeHttps,
            Host = credentials.ServerName,
            Path = "/WebUntis/jsonrpc_intern.do",
            Query = $"school={credentials.School}"
        }.Uri;
        JObject responseJson = await InternalJsonRpcRequestAsync(requestParams, "getUserData2017", requestUri, ct);

        if (responseJson["error"] is JObject error)
        {
            int code = error["code"]!.Value<int>()!;
            string message = error["message"]!.Value<string>()!;

            IEnumerable<WebUntisError> errors = new[] { new WebUntisError(code.ToString(), message) };
            throw new WebUntisException(errors);
        }

        // Creates session from response if successful
        try
        {
            WebUntisSession session = await CreateSessionInternalAsync(credentials.ServerName, ct);

            JObject userData = (JObject)responseJson["userData"]!;
            if (userData["elemType"]!.Value<string>()!.Equals("STUDENT"))
            {
                session._user = new Student
                {
                    Id = userData["elemId"]!.Value<int>(),
                    Displayname = userData["displayName"]!.Value<string>()!
                };
            }
            else
            {
                session._user = new Teacher
                {
                    Id = userData["elemId"]!.Value<int>(),
                    Displayname = userData["displayName"]!.Value<string>()!
                };
            }
            _session = session;

            MasterData masterData = responseJson["masterData"]!.ToObject<MasterData>()!;
            return masterData;
        }
        catch (WebUntisException ex)
            when (ex.Errors.Any(e => e.Code.Equals((-8504).ToString())))     // error code -8504 means 'bad credentials'
        {
            return null;
        }
    }

    private async Task<WebUntisSession> CreateSessionInternalAsync(string server, CancellationToken ct)
    {
        WebUntisSession session = new()
        {
            ServerUri = new UriBuilder
            {
                Scheme = Uri.UriSchemeHttps,
                Host = server
            }.Uri
        };

        Uri jwtRequestUri = new UriBuilder(session.ServerUri)
        {
            Path = "/WebUntis/api/token/new"
        }.Uri;
        string jwtBearer = await InternalApiRequestAsync(jwtRequestUri, ct, skipAuthorization: true);     // authorization is done via cookie
        session.UpdateJwtBearer(jwtBearer);

        return session;
    }

    /// <summary>
    /// Signs out the user (You can reuse the client)
    /// </summary>
    /// <param name="ct">Cancellation token</param>
    /// <exception cref="ObjectDisposedException"></exception>
    public Task SignOutAsync(CancellationToken ct = default)
    {
        ThrowWhenNotAvailable();
        _session = null;

        return Task.CompletedTask;
    }

    /// <summary>
    /// Refreshes the current session
    /// </summary>
    /// <remarks>
    /// Until this action was successfully ended no request should made
    /// </remarks>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A value that indicates whether the reload was successful (when <see langword="false"/> it isn't possible to determine the specific error)</returns>
    /// <exception cref="HttpRequestException"></exception>
    /// <exception cref="WebUntisException"></exception>
    /// <exception cref="InvalidOperationException"></exception>
    /// <exception cref="ObjectDisposedException"></exception>
    public async Task<bool> ReloadSessionAsync(CancellationToken ct = default)
    {
        ThrowWhenNotAvailable();

        string response = await InternalApiRequestAsync("/WebUntis/api/token/new", ct);
        return Session!.UpdateJwtBearer(response);
    }

    private async Task<string> InternalApiRequestAsync(string path, CancellationToken ct, bool skipAuthorization = false)
    {
        ThrowWhenNotAvailable(skipAuthorization);

        UriBuilder uriBuilder = new(Session!.ServerUri)
        {
            Path = path
        };
        using HttpRequestMessage request = new(HttpMethod.Get, uriBuilder.Uri);

        return await InternalApiRequestAsync(request, ct, skipAuthorization);
    }

    private async Task<string> InternalApiRequestAsync(Uri uri, CancellationToken ct, bool skipAuthorization = false)
    {
        using HttpRequestMessage request = new(HttpMethod.Get, uri);
        return await InternalApiRequestAsync(request, ct, skipAuthorization);
    }

    private async Task<string> InternalApiRequestAsync(HttpRequestMessage request, CancellationToken ct, bool skipAuthorization = false)
    {
        ThrowWhenNotAvailable(skipAuthorization);

        if (!skipAuthorization)
        {
            request.Headers.Authorization = new("Bearer", Session!.AuthorizationBearer);
        } 

        using HttpResponseMessage response = await _client.SendAsync(request, ct);

        string responseString = await response.Content.ReadAsStringAsync(ct);
        if (response.StatusCode != HttpStatusCode.OK)
        {
            JObject obj = JObject.Parse(responseString);
            if (obj.ContainsKey("errors"))
            {
                JArray errorArray = (JArray)obj!["errors"]!;
                throw new WebUntisException(errorArray);
            }

            string code = obj["errorCode"]!.Value<string>()!;
            string message = obj["errorMessage"]!.Value<string>()!;

            IEnumerable<WebUntisError> errors = new[] { new WebUntisError(code, message) };
            throw new WebUntisException(errors);
        }

        return responseString;
    }

    private async Task<JObject> InternalJsonRpcRequestAsync(JToken @params, string method, string requestPath = "/WebUntis/jsonrpc.do", CancellationToken ct = default)
    {
        return await InternalJsonRpcRequestAsync(@params, method, new UriBuilder(Session!.ServerUri)
        {
            Path = requestPath
        }.Uri, ct);
    }

    private async Task<JObject> InternalJsonRpcRequestAsync(JToken @params, string method, Uri requestUri, CancellationToken ct = default)
    {
        string requestId = Guid.NewGuid().ToString();
        JObject requestJson = new()
        {
            new JProperty("id", requestId),
            new JProperty("method", method),
            new JProperty("params", @params),
            new JProperty("jsonrpc", "2.0")
        };

        using HttpContent content = new StringContent(requestJson.ToString(), Encoding.UTF8, MediaTypeNames.Application.Json);
        using HttpResponseMessage response = await _client.PostAsync(requestUri, content, ct);

        string responseString = await response.Content.ReadAsStringAsync(ct);
        JObject responseJson = JObject.Parse(responseString);

        if (responseJson["error"] is JObject error)
        {
            int code = error["code"]!.Value<int>()!;
            string message = error["message"]!.Value<string>()!;

            IEnumerable<WebUntisError> errors = new[] { new WebUntisError(code.ToString(), message) };
            throw new WebUntisException(errors);
        }
        else if (responseJson["id"]!.Value<string>() != requestId)
        {
            throw new InvalidOperationException("The received request id does not match the sent one.");
        }

        return (JObject)responseJson["result"]!;
    }

    private void ThrowWhenNotAvailable(bool skipAuthorization = false)
    {
        // Check for disposing
#if NET8_0_OR_GREATER
            ObjectDisposedException.ThrowIf(_disposedValue, this);
#else
        if (_disposedValue)
            throw new ObjectDisposedException(GetType().FullName);
#endif
        if (!skipAuthorization && !IsLoggedIn)
            throw new InvalidOperationException("The client is currently not signed in!");
    }

    #region IDisposable
    private bool _disposedValue;

    /// <inheritdoc/>
    public void Dispose()
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }

    /// <summary>
    /// Dispose
    /// </summary>
    /// <param name="disposing"></param>
    protected virtual void Dispose(bool disposing)
    {
        if (!_disposedValue)
        {
            _session = null;
            _client.CancelPendingRequests();

            if (disposing)
            {
                if (_disposeClient)
                    _client.Dispose();
            }

            _disposedValue = true;
        }
    }

    /// <summary>
    /// Finalizer
    /// </summary>
    ~WebUntisClient()
    {
        Dispose(disposing: false);
    }
    #endregion
}